### ISSUE TITLE
LTN pocket is not detected (no color)

### ISSUE THREAD

**Issue by TFCx** [dabreegster/ltn#50]
I'm pretty sure, I delimited a LTN pocket in this example. Even by checking the route tool, I can't see any road that can lead into (or out of) this pocket (except by out single road in the north). Yet it's still one single color.

![image](https://github.com/dabreegster/ltn/assets/9135500/52160365-353c-42c0-9e65-9ba81199ee5a)

And even by blocking the single access, the sub-district doesn't turn red (even if the route mode doesn't detect any way to get in/out)

**Comment by dabreegster** [comment]
Could you "Export project to GeoJSON" from the "Pick neighbourhood page" and send? (Pastebin, attach here as .txt file, or something else)

Bit hard to tell without fiddling around with it, but it might be because the limited access is due to how you've drawn the one-ways. The cell-finding algorithm only looks at modal filters, not one-ways, to determine this one time. I have an old attempt to look at one-ways too, https://github.com/a-b-street/abstreet/pull/1043, but there must've been some problem with it, or inherent ambiguity with visualizing it.

**Comment by TFCx** [comment]
You're right, I found that the district is not waterproof when not considering one-ways

![image](https://github.com/dabreegster/ltn/assets/9135500/35ee20db-f8d4-4b1a-a322-43ceaec4d44d)

Of course, there's a anomaly here (the middle can't be reached by cars).

By moving the filter, I got a LTN.

![image](https://github.com/dabreegster/ltn/assets/9135500/b0b019bf-a7c6-4c8b-89df-9b9257184f3d)

I'm closing the issue.
